version: '3.9'
services:
  cabinet-api:
    build:
      context: .
      dockerfile: ../Dockerfile
    ports:
      - "5070:5000"
      - "5072:5002"
    environment:
      DatabaseConnectionOptions__ConnectionString: "Host=host.docker.internal;Port=5426;Database=cabinetDb;Username=user;Password=password"

  postgres:
    container_name: cabinet-postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cabinetDb
    command: "-c log_statement=all"
    ports:
      - "3306:3306"

  jaeger:
    container_name: cabinet-jaeger
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
      
  rabbit:
    container_name: cabinet-rabbit
    image: rabbitmq:3.8.7-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_DEFAULT_VHOST: local

  prometheus:
    container_name: cabinet-prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus/
    hostname: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
    networks:
      - default

  node-exporter:
    container_name: cabinet-exporter
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    hostname: exporter
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --collector.filesystem.ignored-mount-points
      - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)
    ports:
      - 9100:9100
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
    networks:
      - default

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16